using System.Reflection;
using AutoFixture;
using AutoFixture.Kernel;
using AutoFixture.Xunit3;

namespace Cabazure.Test.Attributes;

/// <summary>
/// Shared helper for merging explicit theory data rows with fixture-generated values.
/// </summary>
internal static class AutoNSubstituteDataHelper
{
    /// <summary>
    /// Resolves a complete set of theory parameter values by combining <paramref name="provided"/>
    /// values (left-aligned) with fixture-generated values for any remaining parameters.
    /// Parameters of type <see cref="IFixture"/> or <see cref="Fixture"/> receive the fixture
    /// instance used to resolve the remaining parameters.
    /// </summary>
    /// <param name="fixture">The <see cref="IFixture"/> used to generate missing values.</param>
    /// <param name="parameters">All parameters of the theory method.</param>
    /// <param name="provided">
    /// Explicit values for the leading parameters. May be shorter than <paramref name="parameters"/>;
    /// any parameters beyond <c>provided.Length</c> are auto-generated by the fixture.
    /// </param>
    /// <returns>An array containing one resolved value per parameter.</returns>
    internal static object?[] MergeValues(
        IFixture fixture,
        ParameterInfo[] parameters,
        object?[] provided)
    {
        var values = new object?[parameters.Length];

        for (var i = 0; i < parameters.Length; i++)
        {
            var parameter = parameters[i];
            var frozenAttr = parameter.GetCustomAttribute<FrozenAttribute>();

            if (i < provided.Length)
            {
                var value = provided[i];
                values[i] = value;

                if (frozenAttr is not null && value is not null && !parameter.ParameterType.IsValueType)
                {
                    fixture.Customizations.Insert(
                        0,
                        SpecimenBuilderNodeFactory.CreateTypedNode(parameter.ParameterType, new FixedBuilder(value)));
                }
            }
            else if (parameter.ParameterType.IsAssignableFrom(typeof(Fixture)))
            {
                values[i] = fixture;
            }
            else
            {
                if (frozenAttr is not null)
                {
                    // FreezeOnMatchCustomization creates the value AND registers it as frozen
                    // in one step; the subsequent Resolve call returns the already-frozen instance.
                    fixture.Customize(frozenAttr.GetCustomization(parameter));
                }

                values[i] = new SpecimenContext(fixture).Resolve(parameter);
            }
        }

        return values;
    }
}
