using System.Reflection;
using Cabazure.Test.Fixture;

namespace Cabazure.Test.Attributes;

/// <summary>
/// Shared helper for merging explicit theory data rows with <see cref="SutFixture"/>-generated values.
/// </summary>
internal static class AutoNSubstituteDataHelper
{
    /// <summary>
    /// Resolves a complete set of theory parameter values by combining <paramref name="provided"/>
    /// values (left-aligned) with fixture-generated values for any remaining parameters.
    /// </summary>
    /// <param name="fixture">The <see cref="SutFixture"/> used to generate missing values.</param>
    /// <param name="parameters">All parameters of the theory method.</param>
    /// <param name="provided">
    /// Explicit values for the leading parameters. May be shorter than <paramref name="parameters"/>;
    /// any parameters beyond <c>provided.Length</c> are auto-generated by the fixture.
    /// </param>
    /// <returns>An array containing one resolved value per parameter.</returns>
    internal static object?[] MergeValues(
        SutFixture fixture,
        ParameterInfo[] parameters,
        object?[] provided)
    {
        var values = new object?[parameters.Length];

        for (var i = 0; i < parameters.Length; i++)
        {
            var parameter = parameters[i];
            var isFrozen = parameter.GetCustomAttribute<FrozenAttribute>() is not null;

            if (i < provided.Length)
            {
                var value = provided[i];
                values[i] = value;

                if (isFrozen && value is not null && !parameter.ParameterType.IsValueType)
                {
                    FreezeValue(fixture, parameter.ParameterType, value);
                }
            }
            else
            {
                var value = CreateValue(fixture, parameter.ParameterType);
                values[i] = value;

                if (isFrozen && !parameter.ParameterType.IsValueType)
                {
                    FreezeValue(fixture, parameter.ParameterType, value);
                }
            }
        }

        return values;
    }

    internal static object CreateValue(SutFixture fixture, Type type)
    {
        var createMethod = typeof(SutFixture)
            .GetMethod(nameof(SutFixture.Create))!
            .MakeGenericMethod(type);
        return createMethod.Invoke(fixture, null)!;
    }

    internal static void FreezeValue(SutFixture fixture, Type type, object value)
    {
        if (type.IsValueType)
        {
            return;
        }

        var freezeMethod = typeof(SutFixture)
            .GetMethods()
            .First(m => m.Name == nameof(SutFixture.Freeze)
                        && m.GetParameters().Length == 1
                        && m.GetParameters()[0].ParameterType.IsGenericParameter)
            .MakeGenericMethod(type);
        freezeMethod.Invoke(fixture, [value]);
    }
}
