using System.Reflection;
using Xunit;
using Xunit.Sdk;
using Xunit.v3;

namespace Cabazure.Test.Attributes;

/// <summary>
/// An xUnit 3 data attribute that provides theory test method arguments using
/// <see cref="FixtureFactory"/>, with automatic NSubstitute substitution for
/// interface and abstract class parameters.
/// </summary>
/// <remarks>
/// <para>
/// Parameters decorated with <see cref="AutoFixture.Xunit3.FrozenAttribute"/> are frozen in the fixture
/// before subsequent parameters are resolved, so all later parameters that depend on
/// the same type receive the same instance.
/// </para>
/// <example>
/// <code>
/// [Theory, AutoNSubstituteData]
/// public void Test(IMyService service, MyClass sut)
/// {
///     // service is an NSubstitute substitute
///     // sut is created with service injected
/// }
/// </code>
/// </example>
/// </remarks>
public sealed class AutoNSubstituteDataAttribute : DataAttribute
{
    /// <summary>
    /// Returns a single theory data row whose values are fully generated by
    /// <see cref="FixtureFactory"/>. Any disposable arguments are registered with
    /// <paramref name="disposalTracker"/> so xUnit 3 disposes them automatically
    /// after the test case completes.
    /// </summary>
    /// <param name="testMethod">The theory method for which data is being provided.</param>
    /// <param name="disposalTracker">
    /// The xUnit 3 disposal tracker; disposable argument values are registered here
    /// and cleaned up after each test case.
    /// </param>
    /// <returns>A single-element collection containing the generated <see cref="TheoryDataRow"/>.</returns>
    public override ValueTask<IReadOnlyCollection<ITheoryDataRow>> GetData(
        MethodInfo testMethod,
        DisposalTracker disposalTracker)
    {
        ArgumentNullException.ThrowIfNull(testMethod);

        var fixture = AutoNSubstituteDataHelper.CreateFixture(testMethod);
        var parameters = testMethod.GetParameters();
        var values = AutoNSubstituteDataHelper.MergeValues(fixture, parameters, []);
        disposalTracker.AddRange(values);
        IReadOnlyCollection<ITheoryDataRow> result = [new TheoryDataRow(values)];
        return new ValueTask<IReadOnlyCollection<ITheoryDataRow>>(result);
    }

    /// <inheritdoc />
    public override bool SupportsDiscoveryEnumeration() => true;
}
