using System.Reflection;
using Cabazure.Test.Attributes;
using Xunit;
using Xunit.Sdk;
using Xunit.v3;

namespace Cabazure.Test;

/// <summary>
/// An xUnit 3 data attribute that provides theory test method arguments by enumerating rows
/// from an <c>IEnumerable&lt;object[]&gt;</c> data class and filling any remaining parameters
/// using <see cref="FixtureFactory"/>.
/// </summary>
/// <remarks>
/// <para>
/// The data class must have a public parameterless constructor and implement
/// <c>IEnumerable&lt;object[]&gt;</c> or inherit from <c>TheoryData&lt;T1, T2, ...&gt;</c>.
/// Each row is applied to the leading parameters of the theory method. Any parameters
/// not covered by the row are auto-generated by <see cref="FixtureFactory"/>.
/// </para>
/// <para>
/// Parameters decorated with <see cref="AutoFixture.Xunit3.FrozenAttribute"/> are frozen in the fixture
/// before subsequent parameters are resolved.
/// </para>
/// <example>
/// <code>
/// // Option 1: Implement IEnumerable&lt;object[]&gt;
/// public class MyTestData : IEnumerable&lt;object[]&gt;
/// {
///     public IEnumerator&lt;object[]&gt; GetEnumerator()
///     {
///         yield return new object[] { "hello" };
///         yield return new object[] { "world" };
///     }
///     IEnumerator IEnumerable.GetEnumerator() =&gt; GetEnumerator();
/// }
///
/// // Option 2: Inherit from TheoryData&lt;T&gt;
/// public class MyTestData : TheoryData&lt;string&gt;
/// {
///     public MyTestData()
///     {
///         Add("hello");
///         Add("world");
///     }
/// }
///
/// [Theory]
/// [ClassAutoNSubstituteData(typeof(MyTestData))]
/// public void Test(string message, IMyService service)
/// {
///     // message is "hello" or "world"
///     // service is an NSubstitute substitute
/// }
/// </code>
/// </example>
/// </remarks>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
public sealed class ClassAutoNSubstituteDataAttribute(Type dataClass) : ClassDataAttribute(dataClass)
{
    /// <summary>
    /// Returns one theory data row per row supplied by <see cref="ClassDataAttribute.Class"/>, each
    /// merged with fixture-generated values for any remaining parameters. Any disposable
    /// arguments in each row are registered with <paramref name="disposalTracker"/>
    /// so xUnit 3 disposes them automatically after the corresponding test case completes.
    /// </summary>
    /// <param name="testMethod">The theory method for which data is being provided.</param>
    /// <param name="disposalTracker">
    /// The xUnit 3 disposal tracker; disposable argument values are registered here
    /// and cleaned up after each test case.
    /// </param>
    /// <returns>
    /// A collection of <see cref="TheoryDataRow"/> instances, one per row from the data class.
    /// </returns>
    public override async ValueTask<IReadOnlyCollection<ITheoryDataRow>> GetData(
        MethodInfo testMethod,
        DisposalTracker disposalTracker)
    {
        ArgumentNullException.ThrowIfNull(testMethod);

        var baseRows = await base.GetData(testMethod, disposalTracker);
        var theoryParams = testMethod.GetParameters();

        var result = new List<ITheoryDataRow>(baseRows.Count);
        foreach (var baseRow in baseRows)
        {
            var fixture = FixtureFactory.Create(testMethod);
            var values = fixture.MergeValues(theoryParams, baseRow.GetData());
            disposalTracker.AddRange(values);
            result.Add(new TheoryDataRow(values));
        }

        return result;
    }

    /// <inheritdoc />
    public override bool SupportsDiscoveryEnumeration() => true;
}
