using System.Collections;
using System.Reflection;
using Cabazure.Test.Attributes;
using Xunit;
using Xunit.Sdk;
using Xunit.v3;

namespace Cabazure.Test;

/// <summary>
/// An xUnit 3 data attribute that provides theory test method arguments by enumerating rows
/// from an <c>IEnumerable&lt;object[]&gt;</c> data class and filling any remaining parameters
/// using <see cref="FixtureFactory"/>.
/// </summary>
/// <remarks>
/// <para>
/// The data class must have a public parameterless constructor and implement
/// <c>IEnumerable&lt;object[]&gt;</c>. Each row is applied to the leading parameters of the
/// theory method. Any parameters not covered by the row are auto-generated by
/// <see cref="FixtureFactory"/>.
/// </para>
/// <para>
/// Parameters decorated with <see cref="AutoFixture.Xunit3.FrozenAttribute"/> are frozen in the fixture
/// before subsequent parameters are resolved.
/// </para>
/// <example>
/// <code>
/// public class MyTestData : IEnumerable&lt;object[]&gt;
/// {
///     public IEnumerator&lt;object[]&gt; GetEnumerator()
///     {
///         yield return new object[] { "hello" };
///         yield return new object[] { "world" };
///     }
///     IEnumerator IEnumerable.GetEnumerator() =&gt; GetEnumerator();
/// }
///
/// [Theory]
/// [ClassAutoNSubstituteData(typeof(MyTestData))]
/// public void Test(string message, IMyService service)
/// {
///     // message is "hello" or "world"
///     // service is an NSubstitute substitute
/// }
/// </code>
/// </example>
/// </remarks>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
public sealed class ClassAutoNSubstituteDataAttribute : DataAttribute
{
    /// <summary>
    /// Initializes a new instance of <see cref="ClassAutoNSubstituteDataAttribute"/>
    /// with the specified data class.
    /// </summary>
    /// <param name="dataClass">
    /// The type that provides test data. Must have a public parameterless constructor
    /// and implement <c>IEnumerable&lt;object[]&gt;</c>.
    /// </param>
    public ClassAutoNSubstituteDataAttribute(Type dataClass)
    {
        DataClass = dataClass;
    }

    /// <summary>
    /// Gets the type that provides the test data rows.
    /// </summary>
    public Type DataClass { get; }

    /// <summary>
    /// Returns one theory data row per row supplied by the <see cref="DataClass"/>, each
    /// merged with fixture-generated values for any remaining parameters. Any disposable
    /// arguments in each row are registered with <paramref name="disposalTracker"/>
    /// so xUnit 3 disposes them automatically after the corresponding test case completes.
    /// </summary>
    /// <param name="testMethod">The theory method for which data is being provided.</param>
    /// <param name="disposalTracker">
    /// The xUnit 3 disposal tracker; disposable argument values are registered here
    /// and cleaned up after each test case.
    /// </param>
    /// <returns>
    /// A collection of <see cref="TheoryDataRow"/> instances, one per row from the data class.
    /// </returns>
    public override ValueTask<IReadOnlyCollection<ITheoryDataRow>> GetData(
        MethodInfo testMethod,
        DisposalTracker disposalTracker)
    {
        ArgumentNullException.ThrowIfNull(testMethod);

        if (Activator.CreateInstance(DataClass) is not IEnumerable dataInstance)
        {
            throw new InvalidOperationException(
                $"Type '{DataClass.FullName}' must implement IEnumerable<object[]>.");
        }

        var theoryParams = testMethod.GetParameters();

        var result = new List<ITheoryDataRow>();
        foreach (var item in dataInstance)
        {
            var row = item as object?[] ?? [(object?)item];
            var fixture = FixtureFactory.Create(testMethod);
            var values = fixture.MergeValues(theoryParams, row);
            disposalTracker.AddRange(values);
            result.Add(new TheoryDataRow(values));
        }

        return new ValueTask<IReadOnlyCollection<ITheoryDataRow>>(result);
    }

    /// <inheritdoc />
    public override bool SupportsDiscoveryEnumeration() => true;
}
