using System.Collections.Concurrent;
using System.Reflection;
using AutoFixture;
using AutoFixture.Kernel;
using AutoFixture.Xunit3;

namespace Cabazure.Test.Attributes;

/// <summary>
/// Extension methods on <see cref="IFixture"/> for merging explicit theory data rows
/// with fixture-generated values.
/// </summary>
internal static class FixtureDataExtensions
{
    private sealed record CachedParameterAttributes(
        IRequestSpecification? FrozenMatcher,
        CustomizeAttribute[] Customizations);

    private static readonly ConcurrentDictionary<ParameterInfo, CachedParameterAttributes> ParameterCache = new();

    private static CachedParameterAttributes GetParameterAttributes(ParameterInfo parameter)
        => ParameterCache.GetOrAdd(parameter, static p =>
        {
            var frozenAttr = p.GetCustomAttribute<FrozenAttribute>();
            IRequestSpecification? matcher = frozenAttr is not null
                ? ((FreezeOnMatchCustomization)frozenAttr.GetCustomization(p)).Matcher
                : null;
            return new CachedParameterAttributes(
                matcher,
                [.. p.GetCustomAttributes<CustomizeAttribute>()]);
        });

    /// <summary>
    /// Resolves a complete set of theory parameter values by combining <paramref name="provided"/>
    /// values (left-aligned) with fixture-generated values for any remaining parameters.
    /// Parameters of type <see cref="IFixture"/> or <see cref="Fixture"/> receive the fixture
    /// instance used to resolve the remaining parameters.
    /// </summary>
    /// <param name="fixture">The <see cref="IFixture"/> used to generate missing values.</param>
    /// <param name="parameters">All parameters of the theory method.</param>
    /// <param name="provided">
    /// Explicit values for the leading parameters. May be shorter than <paramref name="parameters"/>;
    /// any parameters beyond <c>provided.Length</c> are auto-generated by the fixture.
    /// </param>
    /// <returns>An array containing one resolved value per parameter.</returns>
    internal static object?[] MergeValues(
        this IFixture fixture,
        ParameterInfo[] parameters,
        object?[] provided)
    {
        var values = new object?[parameters.Length];
        for (var i = 0; i < parameters.Length; i++)
        {
            var parameter = parameters[i];
            if (i < provided.Length)
            {
                values[i] = provided[i];
                fixture.FreezeProvided(parameter, provided[i]);
            }
            else
            {
                values[i] = fixture.ResolveAuto(parameter);
            }
        }

        return values;
    }

    /// <summary>
    /// Registers an already-provided value in the fixture when the parameter carries
    /// <see cref="FrozenAttribute"/>, so subsequent parameters of the same type receive
    /// the same instance. Respects the <see cref="FrozenAttribute.By"/> matching flags.
    /// </summary>
    private static void FreezeProvided(this IFixture fixture, ParameterInfo parameter, object? value)
    {
        if (value is null) return;
        var cached = GetParameterAttributes(parameter);
        if (cached.FrozenMatcher is not { } matcher) return;
        fixture.Customizations.Insert(
            0,
            new FilteringSpecimenBuilder(new FixedBuilder(value), matcher));
    }

    /// <summary>
    /// Applies parameter-level <see cref="CustomizeAttribute"/> annotations to the fixture
    /// then resolves a value. Returns the fixture itself for <see cref="IFixture"/> or
    /// <see cref="Fixture"/> parameters.
    /// </summary>
    private static object? ResolveAuto(this IFixture fixture, ParameterInfo parameter)
    {
        if (parameter.ParameterType.IsAssignableFrom(typeof(Fixture)))
            return fixture;

        var cached = GetParameterAttributes(parameter);
        foreach (var attr in cached.Customizations)
            fixture.Customize(attr.GetCustomization(parameter));

        return new SpecimenContext(fixture).Resolve(parameter);
    }
}
