using System.Reflection;
using AutoFixture;
using AutoFixture.Kernel;
using AutoFixture.Xunit3;

namespace Cabazure.Test.Attributes;

/// <summary>
/// Extension methods on <see cref="IFixture"/> for merging explicit theory data rows
/// with fixture-generated values.
/// </summary>
internal static class FixtureDataExtensions
{
    /// <summary>
    /// Resolves a complete set of theory parameter values by combining <paramref name="provided"/>
    /// values (left-aligned) with fixture-generated values for any remaining parameters.
    /// Parameters of type <see cref="IFixture"/> or <see cref="Fixture"/> receive the fixture
    /// instance used to resolve the remaining parameters.
    /// </summary>
    /// <param name="fixture">The <see cref="IFixture"/> used to generate missing values.</param>
    /// <param name="parameters">All parameters of the theory method.</param>
    /// <param name="provided">
    /// Explicit values for the leading parameters. May be shorter than <paramref name="parameters"/>;
    /// any parameters beyond <c>provided.Length</c> are auto-generated by the fixture.
    /// </param>
    /// <returns>An array containing one resolved value per parameter.</returns>
    internal static object?[] MergeValues(
        this IFixture fixture,
        ParameterInfo[] parameters,
        object?[] provided)
    {
        var values = new object?[parameters.Length];

        for (var i = 0; i < parameters.Length; i++)
        {
            var parameter = parameters[i];

            if (i < provided.Length)
            {
                var value = provided[i];
                values[i] = value;

                var frozenAttr = parameter.GetCustomAttribute<FrozenAttribute>();
                if (frozenAttr is not null && value is not null && !parameter.ParameterType.IsValueType)
                {
                    fixture.Customizations.Insert(
                        0,
                        SpecimenBuilderNodeFactory.CreateTypedNode(parameter.ParameterType, new FixedBuilder(value)));
                }
            }
            else if (parameter.ParameterType.IsAssignableFrom(typeof(Fixture)))
            {
                values[i] = fixture;
            }
            else
            {
                foreach (var attr in parameter.GetCustomAttributes<CustomizeAttribute>())
                {
                    fixture.Customize(attr.GetCustomization(parameter));
                }

                values[i] = new SpecimenContext(fixture).Resolve(parameter);
            }
        }

        return values;
    }
}
