using System.Reflection;
using Xunit;
using Xunit.Sdk;
using Xunit.v3;

namespace Cabazure.Test.Attributes;

/// <summary>
/// An xUnit 3 data attribute that provides theory test method arguments by combining
/// explicit inline values with <see cref="FixtureFactory"/>-generated values for any
/// remaining parameters.
/// </summary>
/// <remarks>
/// <para>
/// Inline values are applied to the leading parameters of the theory method left-to-right.
/// Any parameters not covered by the inline values are auto-generated by a <see cref="FixtureFactory"/>.
/// </para>
/// <para>
/// Parameters decorated with <see cref="AutoFixture.Xunit3.FrozenAttribute"/> are frozen in the fixture
/// before subsequent parameters are resolved.
/// </para>
/// <example>
/// <code>
/// [Theory]
/// [InlineAutoNSubstituteData("hello", 42)]
/// public void Test(string message, int count, IMyService service)
/// {
///     // message == "hello", count == 42
///     // service is an NSubstitute substitute
/// }
/// </code>
/// </example>
/// </remarks>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
public sealed class InlineAutoNSubstituteDataAttribute : DataAttribute
{
    /// <summary>
    /// Initializes a new instance of <see cref="InlineAutoNSubstituteDataAttribute"/>
    /// with the specified inline values.
    /// </summary>
    /// <param name="values">The explicit values for the leading theory parameters.</param>
    public InlineAutoNSubstituteDataAttribute(params object?[] values)
    {
        Values = values;
    }

    /// <summary>
    /// Gets the explicit inline values for the leading theory parameters.
    /// </summary>
    public object?[] Values { get; }

    /// <summary>
    /// Returns a single theory data row that merges the inline <see cref="Values"/>
    /// with fixture-generated values for any remaining parameters. Any disposable
    /// arguments are registered with <paramref name="disposalTracker"/> so xUnit 3
    /// disposes them automatically after the test case completes.
    /// </summary>
    /// <param name="testMethod">The theory method for which data is being provided.</param>
    /// <param name="disposalTracker">
    /// The xUnit 3 disposal tracker; disposable argument values are registered here
    /// and cleaned up after each test case.
    /// </param>
    /// <returns>A single-element collection containing the merged <see cref="TheoryDataRow"/>.</returns>
    public override ValueTask<IReadOnlyCollection<ITheoryDataRow>> GetData(
        MethodInfo testMethod,
        DisposalTracker disposalTracker)
    {
        ArgumentNullException.ThrowIfNull(testMethod);

        var fixture = FixtureFactory.Create(testMethod);
        var parameters = testMethod.GetParameters();
        var values = AutoNSubstituteDataHelper.MergeValues(fixture, parameters, Values);
        disposalTracker.AddRange(values);
        IReadOnlyCollection<ITheoryDataRow> result = [new TheoryDataRow(values)];
        return new ValueTask<IReadOnlyCollection<ITheoryDataRow>>(result);
    }

    /// <inheritdoc />
    public override bool SupportsDiscoveryEnumeration() => true;
}
