using System.Collections;
using System.Reflection;
using Xunit;
using Xunit.Sdk;
using Xunit.v3;

namespace Cabazure.Test.Attributes;

/// <summary>
/// An xUnit 3 data attribute that provides theory test method arguments by reading rows
/// from a static member (property, field, or method) and filling any remaining parameters
/// using <see cref="FixtureFactory"/>.
/// </summary>
/// <remarks>
/// <para>
/// The member must be <c>static</c> and return <c>IEnumerable&lt;object[]&gt;</c>.
/// Each row from the member is applied to the leading parameters of the theory method.
/// Any parameters not covered by the row are auto-generated by <see cref="FixtureFactory"/>.
/// </para>
/// <para>
/// By default the member is looked up on the test class. Set <see cref="MemberType"/> to
/// resolve the member on a different type.
/// </para>
/// <para>
/// Parameters decorated with <see cref="AutoFixture.Xunit3.FrozenAttribute"/> are frozen in the fixture
/// before subsequent parameters are resolved.
/// </para>
/// <example>
/// <code>
/// public static IEnumerable&lt;object[]&gt; MyData =&gt; new[]
/// {
///     new object[] { "hello" },
///     new object[] { "world" },
/// };
///
/// [Theory]
/// [MemberAutoNSubstituteData(nameof(MyData))]
/// public void Test(string message, IMyService service)
/// {
///     // message is "hello" or "world"
///     // service is an NSubstitute substitute
/// }
/// </code>
/// </example>
/// </remarks>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
public sealed class MemberAutoNSubstituteDataAttribute : DataAttribute
{
    /// <summary>
    /// Initializes a new instance of <see cref="MemberAutoNSubstituteDataAttribute"/>
    /// with the specified member name and optional arguments for method members.
    /// </summary>
    /// <param name="memberName">The name of the static member that provides the data rows.</param>
    /// <param name="parameters">Optional arguments to pass if the member is a method.</param>
    public MemberAutoNSubstituteDataAttribute(string memberName, params object?[] parameters)
    {
        MemberName = memberName;
        Parameters = parameters;
    }

    /// <summary>
    /// Gets the name of the static member that provides the data rows.
    /// </summary>
    public string MemberName { get; }

    /// <summary>
    /// Gets the optional arguments forwarded to the member if it is a method.
    /// </summary>
    public object?[] Parameters { get; }

    /// <summary>
    /// Gets or sets the type that declares the member. Defaults to the test class
    /// when <see langword="null"/>.
    /// </summary>
    public Type? MemberType { get; set; }

    /// <summary>
    /// Returns one theory data row per row supplied by the named member, each merged
    /// with fixture-generated values for any remaining parameters. Any disposable
    /// arguments in each row are registered with <paramref name="disposalTracker"/>
    /// so xUnit 3 disposes them automatically after the corresponding test case completes.
    /// </summary>
    /// <param name="testMethod">The theory method for which data is being provided.</param>
    /// <param name="disposalTracker">
    /// The xUnit 3 disposal tracker; disposable argument values are registered here
    /// and cleaned up after each test case.
    /// </param>
    /// <returns>
    /// A collection of <see cref="TheoryDataRow"/> instances, one per row from the member.
    /// </returns>
    public override ValueTask<IReadOnlyCollection<ITheoryDataRow>> GetData(
        MethodInfo testMethod,
        DisposalTracker disposalTracker)
    {
        ArgumentNullException.ThrowIfNull(testMethod);

        var declaringType = MemberType ?? testMethod.DeclaringType
            ?? throw new InvalidOperationException(
                "Cannot determine the declaring type. Set MemberType explicitly.");

        var theoryParams = testMethod.GetParameters();
        var rows = GetMemberData(declaringType);

        var result = new List<ITheoryDataRow>();
        foreach (var row in rows)
        {
            var fixture = AutoNSubstituteDataHelper.CreateFixture(testMethod);
            var values = AutoNSubstituteDataHelper.MergeValues(fixture, theoryParams, row);
            disposalTracker.AddRange(values);
            result.Add(new TheoryDataRow(values));
        }

        return new ValueTask<IReadOnlyCollection<ITheoryDataRow>>(result);
    }

    /// <inheritdoc />
    public override bool SupportsDiscoveryEnumeration() => true;

    private IEnumerable<object?[]> GetMemberData(Type type)
    {
        const BindingFlags flags = BindingFlags.Public | BindingFlags.Static;

        var property = type.GetProperty(MemberName, flags);
        if (property is not null)
        {
            return ToRows(property.GetValue(null), MemberName, type);
        }

        var field = type.GetField(MemberName, flags);
        if (field is not null)
        {
            return ToRows(field.GetValue(null), MemberName, type);
        }

        var method = type.GetMethod(MemberName, flags);
        if (method is not null)
        {
            var args = Parameters.Length > 0 ? (object?[])Parameters : null;
            return ToRows(method.Invoke(null, args), MemberName, type);
        }

        throw new InvalidOperationException(
            $"No public static member named '{MemberName}' was found on '{type.FullName}'. " +
            "The member must be a property, field, or method that returns IEnumerable<object[]>.");
    }

    private static IEnumerable<object?[]> ToRows(object? value, string memberName, Type type)
    {
        if (value is not IEnumerable enumerable)
        {
            throw new InvalidOperationException(
                $"Member '{memberName}' on '{type.FullName}' must return IEnumerable<object[]>.");
        }

        return enumerable.Cast<object?>().Select(item => item as object?[] ?? [(object?)item]);
    }
}
