using System.Reflection;
using Cabazure.Test.Attributes;
using Xunit;
using Xunit.Sdk;
using Xunit.v3;

namespace Cabazure.Test;

/// <summary>
/// An xUnit 3 data attribute that provides theory test method arguments by reading rows
/// from a static member (property, field, or method) and filling any remaining parameters
/// using <see cref="FixtureFactory"/>.
/// </summary>
/// <remarks>
/// <para>
/// The member must be <c>static</c> and return <c>IEnumerable&lt;object[]&gt;</c> or
/// a <c>TheoryData&lt;T1, T2, ...&gt;</c> subclass. Each row from the member is applied
/// to the leading parameters of the theory method. Any parameters not covered by the row
/// are auto-generated by <see cref="FixtureFactory"/>.
/// </para>
/// <para>
/// By default the member is looked up on the test class. Set <see cref="MemberDataAttributeBase.MemberType"/> to
/// resolve the member on a different type.
/// </para>
/// <para>
/// Parameters decorated with <see cref="AutoFixture.Xunit3.FrozenAttribute"/> are frozen in the fixture
/// before subsequent parameters are resolved.
/// </para>
/// <example>
/// <code>
/// // Option 1: IEnumerable&lt;object[]&gt;
/// public static IEnumerable&lt;object[]&gt; MyData =&gt; new[]
/// {
///     new object[] { "hello" },
///     new object[] { "world" },
/// };
///
/// // Option 2: TheoryData&lt;T&gt;
/// public static TheoryData&lt;string&gt; MyData =&gt; new() { "hello", "world" };
///
/// [Theory]
/// [MemberAutoNSubstituteData(nameof(MyData))]
/// public void Test(string message, IMyService service)
/// {
///     // message is "hello" or "world"
///     // service is an NSubstitute substitute
/// }
/// </code>
/// </example>
/// </remarks>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
public sealed class MemberAutoNSubstituteDataAttribute : MemberDataAttributeBase
{
    /// <summary>
    /// Initializes a new instance of <see cref="MemberAutoNSubstituteDataAttribute"/>
    /// with the specified member name and optional arguments for method members.
    /// </summary>
    /// <param name="memberName">The name of the static member that provides the data rows.</param>
    /// <param name="parameters">Optional arguments to pass if the member is a method.</param>
    public MemberAutoNSubstituteDataAttribute(string memberName, params object?[] parameters)
        : base(memberName, parameters)
    {
    }

    /// <summary>
    /// Returns one theory data row per row supplied by the named member, each merged
    /// with fixture-generated values for any remaining parameters. Any disposable
    /// arguments in each row are registered with <paramref name="disposalTracker"/>
    /// so xUnit 3 disposes them automatically after the corresponding test case completes.
    /// </summary>
    /// <param name="testMethod">The theory method for which data is being provided.</param>
    /// <param name="disposalTracker">
    /// The xUnit 3 disposal tracker; disposable argument values are registered here
    /// and cleaned up after each test case.
    /// </param>
    /// <returns>
    /// A collection of <see cref="TheoryDataRow"/> instances, one per row from the member.
    /// </returns>
    public override async ValueTask<IReadOnlyCollection<ITheoryDataRow>> GetData(
        MethodInfo testMethod,
        DisposalTracker disposalTracker)
    {
        if (testMethod is null) throw new ArgumentNullException(nameof(testMethod));
        MemberType ??= testMethod.DeclaringType;

        var baseRows = await base.GetData(testMethod, disposalTracker);
        var theoryParams = testMethod.GetParameters();

        var result = new List<ITheoryDataRow>(baseRows.Count);
        foreach (var baseRow in baseRows)
        {
            var fixture = FixtureFactory.Create(testMethod);
            var values = fixture.MergeValues(theoryParams, baseRow.GetData());
            disposalTracker.AddRange(values);
            result.Add(new TheoryDataRow(values));
        }

        return result;
    }

    /// <inheritdoc />
    public override bool SupportsDiscoveryEnumeration() => true;
}
