using System.Collections;
using FrozenAttribute = AutoFixture.Xunit3.FrozenAttribute;
using Cabazure.Test.Tests.Fixture;
using FluentAssertions;
using Xunit;

namespace Cabazure.Test.Tests.Attributes;

public class ClassAutoNSubstituteDataAttributeTests
{
    [Theory]
    [ClassAutoNSubstituteData(typeof(SingleColumnData))]
    public void ClassData_ProvidesRows(
        string value,
        FixtureFactoryTests.IMyInterface service)
    {
        value.Should().BeOneOf("hello", "world");
        service.Should().NotBeNull();
    }

    [Theory]
    [ClassAutoNSubstituteData(typeof(MultiColumnData))]
    public void ClassData_MultipleColumns_ArePassedThrough(
        string message,
        int count,
        FixtureFactoryTests.IMyInterface service)
    {
        message.Should().BeOneOf("hello", "world");
        count.Should().BeOneOf(1, 2);
        service.Should().NotBeNull();
    }

    [Theory]
    [ClassAutoNSubstituteData(typeof(SingleColumnData))]
    public void FrozenAutoParameter_InjectsSameInstanceIntoSut(
        string _,
        [Frozen] FixtureFactoryTests.IMyInterface service,
        FixtureFactoryTests.MyServiceWithDependency sut)
    {
        sut.Dependency.Should().BeSameAs(service);
    }

    [Theory]
    [ClassAutoNSubstituteData(typeof(InterfaceSubstituteData))]
    public void FrozenProvidedValue_InjectsSameInstanceIntoAutoGeneratedSut(
        [Frozen] FixtureFactoryTests.IMyInterface service,
        FixtureFactoryTests.MyServiceWithDependency sut)
    {
        sut.Dependency.Should().BeSameAs(service);
    }

    [Theory]
    [ClassAutoNSubstituteData(typeof(TypedTheoryData))]
    public void ClassData_TheoryDataRows_AreUnpackedCorrectly(
        string message,
        int count,
        FixtureFactoryTests.IMyInterface service)
    {
        message.Should().BeOneOf("hello", "world");
        count.Should().BeOneOf(1, 2);
        service.Should().NotBeNull();
    }

    [Theory]
    [ClassAutoNSubstituteData(typeof(DisposableData))]
    public void DisposableDataClass_ProvidesRows(
        string value,
        FixtureFactoryTests.IMyInterface service)
    {
        value.Should().Be("disposed");
        service.Should().NotBeNull();
    }

    [Fact]
    public void SupportsDiscoveryEnumeration_ReturnsTrue_EvenForDisposableDataClass()
    {
        var sut = new ClassAutoNSubstituteDataAttribute(typeof(DisposableData));
        sut.SupportsDiscoveryEnumeration().Should().BeTrue();
    }
}

public class SingleColumnData : IEnumerable<object[]>
{
    public IEnumerator<object[]> GetEnumerator()
    {
        yield return ["hello"];
        yield return ["world"];
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}

public class MultiColumnData : IEnumerable<object[]>
{
    public IEnumerator<object[]> GetEnumerator()
    {
        yield return ["hello", 1];
        yield return ["world", 2];
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}

public class InterfaceSubstituteData : IEnumerable<object[]>
{
    public IEnumerator<object[]> GetEnumerator()
    {
        yield return [NSubstitute.Substitute.For<FixtureFactoryTests.IMyInterface>()];
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}

public class TypedTheoryData : TheoryData<string, int>
{
    public TypedTheoryData()
    {
        Add("hello", 1);
        Add("world", 2);
    }
}

public class DisposableData : IEnumerable<object[]>, IDisposable
{
    public IEnumerator<object[]> GetEnumerator()
    {
        yield return ["disposed"];
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

    public void Dispose() { }
}
