using System.Collections;
using FluentAssertions;
using Xunit.Sdk;

namespace Cabazure.Test.Tests.Attributes;

public class DisposalTrackerIntegrationTests
{
    [Fact]
    public async Task AutoNSubstituteData_IDisposableParameter_IsDisposedWhenTrackerDisposed()
    {
        var disposalTracker = new DisposalTracker();
        var methodInfo = typeof(DisposalTestMethodHost)
            .GetMethod(nameof(DisposalTestMethodHost.WithTrackableDisposable))!;
        var attr = new AutoNSubstituteDataAttribute();

        var rows = await attr.GetData(methodInfo, disposalTracker);

        var tracked = (TrackableDisposable)rows.Single().GetData()[0]!;

        await disposalTracker.DisposeAsync();

        tracked.IsDisposed.Should().BeTrue();
    }

    [Fact]
    public async Task AutoNSubstituteData_IAsyncDisposableParameter_IsAsyncDisposedWhenTrackerDisposed()
    {
        var disposalTracker = new DisposalTracker();
        var methodInfo = typeof(DisposalTestMethodHost)
            .GetMethod(nameof(DisposalTestMethodHost.WithTrackableAsyncDisposable))!;
        var attr = new AutoNSubstituteDataAttribute();

        var rows = await attr.GetData(methodInfo, disposalTracker);

        var tracked = (TrackableAsyncDisposable)rows.Single().GetData()[0]!;

        await disposalTracker.DisposeAsync();

        tracked.IsDisposed.Should().BeTrue();
    }

    [Fact]
    public async Task AutoNSubstituteData_NonDisposableParameter_TrackerDisposeCompletesWithoutException()
    {
        var disposalTracker = new DisposalTracker();
        var methodInfo = typeof(DisposalTestMethodHost)
            .GetMethod(nameof(DisposalTestMethodHost.WithString))!;
        var attr = new AutoNSubstituteDataAttribute();

        await attr.GetData(methodInfo, disposalTracker);

        Func<Task> act = async () => await disposalTracker.DisposeAsync();

        await act.Should().NotThrowAsync();
    }

    [Fact]
    public async Task InlineAutoNSubstituteData_AutoGeneratedIDisposableParameter_IsDisposedWhenTrackerDisposed()
    {
        var disposalTracker = new DisposalTracker();
        var methodInfo = typeof(DisposalTestMethodHost)
            .GetMethod(nameof(DisposalTestMethodHost.InlineWithTrackableDisposable))!;
        var attr = new InlineAutoNSubstituteDataAttribute("inlineValue");

        var rows = await attr.GetData(methodInfo, disposalTracker);

        // index 1 = the auto-generated TrackableDisposable parameter (index 0 is the inline string)
        var tracked = (TrackableDisposable)rows.Single().GetData()[1]!;

        await disposalTracker.DisposeAsync();

        tracked.IsDisposed.Should().BeTrue();
    }

    [Fact]
    public async Task ClassAutoNSubstituteData_MultipleRows_EachRowDisposablesTrackedAndDisposedIndependently()
    {
        var disposalTracker = new DisposalTracker();
        var methodInfo = typeof(DisposalTestMethodHost)
            .GetMethod(nameof(DisposalTestMethodHost.WithTrackableDisposable))!;
        var attr = new ClassAutoNSubstituteDataAttribute(typeof(TwoEmptyRowsData));

        var rows = (await attr.GetData(methodInfo, disposalTracker)).ToList();

        rows.Should().HaveCount(2);
        var tracked1 = (TrackableDisposable)rows[0].GetData()[0]!;
        var tracked2 = (TrackableDisposable)rows[1].GetData()[0]!;

        tracked1.Should().NotBeSameAs(tracked2, "each row gets its own fixture-generated instance");

        await disposalTracker.DisposeAsync();

        tracked1.IsDisposed.Should().BeTrue();
        tracked2.IsDisposed.Should().BeTrue();
    }
}

/// <summary>
/// Hosts methods whose signatures are used via reflection to drive <c>GetData()</c> calls in tests.
/// The methods themselves are never invoked; they exist only to provide <see cref="System.Reflection.MethodInfo"/>.
/// </summary>
public class DisposalTestMethodHost
{
    public void WithTrackableDisposable(TrackableDisposable disposable) { }
    public void WithTrackableAsyncDisposable(TrackableAsyncDisposable disposable) { }
    public void WithString(string value) { }
    public void InlineWithTrackableDisposable(string inline, TrackableDisposable disposable) { }
}

/// <summary>
/// Tracks whether <see cref="Dispose"/> has been called, for use in <c>DisposalTracker</c> tests.
/// </summary>
public sealed class TrackableDisposable : IDisposable
{
    public bool IsDisposed { get; private set; }
    public void Dispose() => IsDisposed = true;
}

/// <summary>
/// Tracks whether <see cref="DisposeAsync"/> has been called, for use in <c>DisposalTracker</c> tests.
/// </summary>
public sealed class TrackableAsyncDisposable : IAsyncDisposable
{
    public bool IsDisposed { get; private set; }

    public ValueTask DisposeAsync()
    {
        IsDisposed = true;
        return ValueTask.CompletedTask;
    }
}

/// <summary>
/// Provides two empty rows so that <c>ClassAutoNSubstituteDataAttribute</c> auto-generates
/// all parameters for each row — including disposable ones.
/// </summary>
public class TwoEmptyRowsData : IEnumerable<object[]>
{
    public IEnumerator<object[]> GetEnumerator()
    {
        yield return [];
        yield return [];
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}
