using FrozenAttribute = AutoFixture.Xunit3.FrozenAttribute;
using Cabazure.Test.Tests.Fixture;
using AwesomeAssertions;
using Xunit;

namespace Cabazure.Test.Tests.Attributes;

public class InlineAutoNSubstituteDataAttributeTests
{
    [Theory]
    [InlineAutoNSubstituteData("hello")]
    public void InlineValue_IsPassedThrough(
        string value,
        FixtureFactoryTests.IMyInterface service)
    {
        value.Should().Be("hello");
        service.Should().NotBeNull();
    }

    [Theory]
    [InlineAutoNSubstituteData("hello", 42)]
    public void MultipleInlineValues_ArePassedThrough(
        string message,
        int count,
        FixtureFactoryTests.IMyInterface service)
    {
        message.Should().Be("hello");
        count.Should().Be(42);
        service.Should().NotBeNull();
    }

    [Theory]
    [InlineAutoNSubstituteData("first")]
    [InlineAutoNSubstituteData("second")]
    public void MultipleDeclarations_YieldMultipleRows(string value)
    {
        value.Should().BeOneOf("first", "second");
    }

    [Theory]
    [InlineAutoNSubstituteData]
    public void NoInlineValues_AutoGeneratesAllParameters(
        string value,
        FixtureFactoryTests.IMyInterface service)
    {
        value.Should().NotBeNullOrEmpty();
        service.Should().NotBeNull();
    }

    [Theory]
    [InlineAutoNSubstituteData]
    public void FrozenParameter_InjectsSameInstanceIntoSut(
        [Frozen] FixtureFactoryTests.IMyInterface service,
        FixtureFactoryTests.MyServiceWithDependency sut)
    {
        sut.Dependency.Should().BeSameAs(service);
    }

    [Theory]
    [InlineAutoNSubstituteData("hello")]
    public void FrozenInlineValue_InjectsSameStringIntoAutoGeneratedSut(
        [Frozen] string message,
        FixtureFactoryTests.MyServiceWithStringMessage sut)
    {
        sut.Message.Should().Be("hello");
    }

    [Theory]
    [InlineAutoNSubstituteData(null)]
    public void NullInlineReferenceValue_IsPassedThrough(
        string? value,
        FixtureFactoryTests.IMyInterface service)
    {
        value.Should().BeNull();
        service.Should().NotBeNull();
    }

    [Theory]
    [InlineAutoNSubstituteData(null)]
    public void NullInlineNullableValue_IsPassedThrough(
        bool? enabled,
        FixtureFactoryTests.IMyInterface service)
    {
        enabled.Should().BeNull();
        service.Should().NotBeNull();
    }
}
